# Generated by Django 3.2.6 on 2021-08-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dependants', models.IntegerField()),
                ('applicant_income', models.IntegerField()),
                ('coapplicant_income', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('loan_term', models.IntegerField()),
                ('credit_history', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=15)),
                ('married', models.CharField(choices=[('Yes', 'Married'), ('No', 'Single')], max_length=15)),
                ('graduate_info', models.CharField(choices=[('Graduate', 'Graduated'), ('Not_Graduate', 'Not_Graduated')], max_length=30)),
                ('self_employed', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=10)),
                ('area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('urban', 'Urban')], max_length=20)),
            ],
        ),
    ]
