# Generated by Django 3.2.6 on 2021-08-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0002_alter_approval_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='loan_term',
            field=models.PositiveIntegerField(),
        ),
    ]
