# Generated by Django 3.2.6 on 2021-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0003_alter_approval_loan_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='applicant_income',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='approval',
            name='coapplicant_income',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='approval',
            name='dependants',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='approval',
            name='loan_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
