# Generated by Django 3.2.6 on 2021-08-29 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0004_auto_20210829_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
