# Generated by Django 3.2.6 on 2021-08-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0006_auto_20210829_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='Dependants',
            new_name='Dependents',
        ),
        migrations.AlterField(
            model_name='approval',
            name='LoanAmount',
            field=models.FloatField(),
        ),
    ]
