# Generated by Django 3.2.6 on 2021-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0007_auto_20210829_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='Education',
            field=models.CharField(choices=[('Graduate', 'Graduated'), ('Not Graduate', 'Not_Graduated')], max_length=30),
        ),
    ]
