# Generated by Django 3.2.6 on 2021-08-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0008_alter_approval_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='Last_name',
        ),
    ]
