# Generated by Django 3.2.6 on 2021-08-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0009_auto_20210829_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='Property_Area',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=20),
        ),
    ]
