# Generated by Django 3.2.6 on 2021-08-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0010_alter_approval_property_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='Email',
            field=models.EmailField(default='ola@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approval',
            name='First_name',
            field=models.CharField(default='Olamidun', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approval',
            name='Last_name',
            field=models.CharField(default='Olalekan', max_length=50),
            preserve_default=False,
        ),
    ]
