# Generated by Django 3.2.6 on 2021-08-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0013_approval_eligibility_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='eligibility_status',
            new_name='eligible_for_loan',
        ),
        migrations.AlterField(
            model_name='approval',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
