# Generated by Django 3.2.6 on 2021-09-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0014_auto_20210831_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='Dependents',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('3+', '3+')], max_length=2),
        ),
    ]
