# Generated by Django 3.2.6 on 2021-09-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanway_app', '0016_alter_approval_dependents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='Email',
        ),
    ]
